##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Popup floating windows (TUI apps from waybar)
windowrule {
    name = popup-float
    match:class = popup
    float = yes
    center = yes
    size = 900 600
}

