# hyprland.conf
#
source = $HOME/larzuk/dots/ui/hypr/hyprland/monitors.conf
source = $HOME/larzuk/dots/ui/hypr/hyprland/programs.conf
source = $HOME/larzuk/dots/ui/hypr/hyprland/autostart.conf
source = $HOME/larzuk/dots/ui/hypr/hyprland/env.conf
source = $HOME/larzuk/dots/ui/hypr/hyprland/appearance.conf
source = $HOME/larzuk/dots/ui/hypr/hyprland/input.conf
source = $HOME/larzuk/dots/ui/hypr/hyprland/keybinds.conf
source = $HOME/larzuk/dots/ui/hypr/hyprland/windows.conf
